// Every username that posts or comments. flair = default (a comment's own flair overrides it).
// admin: true = ADMIN badge, pesukim and Chazal only. Bios are in-character flavor; keep them true to the person.
users({
  // ---- the Admin ----
  HaMelech:          { admin: true, avatar: "👑", flair: "ADMIN", bio: "Speaks here only in pesukim and the words of Chazal, cited. Nobody puts words in His mouth." },

  // ---- Tanach ----
  Moshe_Rabbeinu:    { avatar: "🧔", flair: "Leader · verified", bio: "Shepherd, then leader of a very stiff-necked nation. Forty days up the mountain, three times. Humblest man on earth (Bamidbar 12:3), so he'd never write that here." },
  Aharon_HaKohen:    { avatar: "🕯️", flair: "Kohen Gadol · first one", bio: "Moshe's older brother. Loves peace, pursues peace. Would like everyone to stop bringing up the calf." },
  Yehoshua_bin_Nun:  { avatar: "🛡️", flair: "OP's attendant", bio: "Moshe's attendant. Never left the tent. Later led the nation into the Land." },
  Yeshayahu_HaNavi:  { avatar: "📯", flair: "Nevi'im · verified", bio: "Prophet in Jerusalem. Big on comfort, bigger on consequences." },
  Yonah_ben_Amitai:  { avatar: "🐋", flair: "Nevi'im · verified", bio: "Prophet. Once took a ship the wrong way. Spent three days in a fish. Wrote the shortest sermon on record: five words." },
  Zecharia_HaNavi:   { avatar: "🔮", flair: "verified", bio: "One of the last prophets. Posts future updates." },
  Torah_Narrator:    { avatar: "📖", flair: "verified", bio: "Posts the pesukim as written. No commentary." },
  Klal_Yisrael:      { avatar: "✡️", bio: "600,000 accounts sharing one login." },
  Melech_Nineveh:    { avatar: "🤴", flair: "King · sackcloth edition", bio: "King of Nineveh, the great city. Traded the throne for ashes when a five-word sermon landed. Very proud of how humble he got." },
  Nineveh_Resident:  { avatar: "🏚️", flair: "reformed", bio: "Lives in Nineveh. Gave the stolen beam back. The palace is a work in progress." },
  Tarshish_Sailor:   { avatar: "⚓", flair: "deckhand", bio: "Ship to Tarshish, one trip. Rowed hard. Prayed harder." },
  random_cow:        { avatar: "🐄", bio: "Nineveh livestock. Fasted once, involuntarily." },
  Sancheriv_genealogy: { avatar: "🏺", flair: "history nerd", bio: "Tracks which enemies' descendants ended up teaching Torah. The list is longer than you think." },
  Yaakov_Avinu:      { avatar: "⭐", flair: "Avos", bio: "Avinu. Blessed his grandsons Ephraim and Menashe. Kids still get that blessing on Simchas Torah." },
  Shlomo_HaMelech:   { avatar: "🦁", flair: "King · verified", bio: "Built the Beis HaMikdash. Wisest of all men. Threw a fourteen-day dedication party." },

  // ---- Tannaim & Amoraim ----
  Rashi:             { avatar: "📜", flair: "Parshan · verified", bio: "11th-c. France. Wine merchant. Explains everything in five words." },
  Rambam_1138:       { avatar: "⚕️", flair: "verified", bio: "Physician, philosopher, codifier. Wrote down every halacha in fourteen books so you wouldn't have to guess." },
  R_Akiva:           { avatar: "🐑", flair: "Tanna", bio: "Shepherd who started learning at forty. 24,000 students. Derives heaps of halachos from the crowns on the letters." },
  R_Eliezer:         { avatar: "🌳", flair: "Tanna", bio: "R' Eliezer ben Hurkenus. A sealed cistern that never loses a drop. Has a carob tree that moves on request." },
  R_Yehoshua_ben_Chanania: { avatar: "🎶", flair: "Levi · Tanna", bio: "Sang on the Temple platform as a young Levi. Later said “it is not in heaven.” Didn't sleep through Sukkos." },
  Hillel_HaZaken:    { avatar: "🕊️", flair: "Nasi", bio: "Nasi. Famously patient. Came from Bavel with nothing and became the head of the Sanhedrin." },
  Shemaya:           { avatar: "📘", flair: "verified", bio: "Nasi, descended from converts. Motto: love work, hate positions of power." },
  Avtalyon:          { avatar: "📗", flair: "verified", bio: "Av Beis Din, descended from converts. Motto: sages, be careful with your words." },
  RabbanShimonBG:    { avatar: "🪢", flair: "Nasi", bio: "Rabban Shimon ben Gamliel. Ranks the best days of the year. Also juggles torches." },
  Yochanan_ben_Zakai: { avatar: "🚪", flair: "Tanna", bio: "Saved Yavneh and its sages. Talked to the Heichal doors when they opened on their own." },
  Abba_Shaul:        { avatar: "🌙", flair: "Tanna", bio: "Tanna. Keeps notes on customs and where they went wrong." },
  Mechilta:          { avatar: "📙", flair: "Midrash Halacha", bio: "Tannaitic midrash on Shemos. Reads between the lines of every verse." },
  R_Yochanan:        { avatar: "🎙️", flair: "Amora", bio: "R' Yochanan bar Nafcha, head of the yeshiva in Teveria. Famously handsome. Quotes the Thirteen Attributes on request." },
  R_Abahu:           { avatar: "🏛️", flair: "Amora", bio: "Amora in Caesarea. Says the things that couldn't be said if they weren't written." },
  R_Zeira:           { avatar: "🚶", flair: "Amora", bio: "Amora. Walks back and forth in front of people who owe him an apology, to make it easy for them." },
  Rav_Abba_Arikha:   { avatar: "🎓", flair: "Amora", bio: "Rav. Founded the yeshiva in Sura. Very tall. Knows how to apologize (thirteen times)." },
  R_Yirmiyah:        { avatar: "❓", flair: "Amora", bio: "Amora. Asks the question everyone else is afraid to ask." },
  R_Elazar:          { avatar: "🐂", flair: "Amora", bio: "Amora. Counted the Sukkos bulls and knows who they were for." },
  Resh_Lakish:       { avatar: "💪", flair: "Talmid", bio: "Former gladiator. Now R' Yochanan's study partner. Brings 24 questions to every answer." },
  Rav_Yosef:         { avatar: "🫙", flair: "Talmid", bio: "Amora in Pumbedisa. Keeps the broken tablets next to the whole ones." },
  Rava:              { avatar: "⚖️", flair: "Amora", bio: "Amora in Mechoza. If it's making you suffer, you're exempt. That's the rule." },
  Levi_bar_Sisi:     { avatar: "🔪", flair: "Amora", bio: "Talmid of Rebbi. Juggled eight knives once. Would like you not to try." },
  Taanis_30b:        { avatar: "📄", flair: "Gemara", bio: "The page of Gemara with six reasons Tu B'Av is a happy day." },
  Taanis_31a:        { avatar: "📄", flair: "Gemara", bio: "The page of Gemara that covers the dancing in the vineyards." },
  Yoma_13a:          { avatar: "📄", flair: "Gemara", bio: "The page of Gemara that tries to make R' Yehuda's backup wife work. It gets complicated." },
  R_Yitzchak_ben_Tavlai: { avatar: "🌲", flair: "Amora", bio: "Amora. Knows why the Mikdash is called Levanon: it makes sins white." },
  RH_31b:            { avatar: "📄", flair: "Gemara", bio: "The page of Gemara that covers the red string." },
  Gemara_AZ:         { avatar: "📄", flair: "Gemara", bio: "Avodah Zarah 3a. Answers the nations' complaints, respectfully." },
  Bereishis_Rabbah:  { avatar: "📕", flair: "Midrash", bio: "The Midrash on Bereishis. Has a lot to say about one letter." },
  Midrash_body_parts: { avatar: "🫀", flair: "Vayikra Rabbah", bio: "Vayikra Rabbah, on the four minim as the four parts of you." },
  Shimon_HaTzadik_era: { avatar: "🗃️", flair: "archivist", bio: "Keeps the records from the forty years of Shimon HaTzadik." },
  Zecharia_ben_Kevutal: { avatar: "📚", flair: "night-shift reader", bio: "Read to the Kohen Gadol all night, many times. From Daniel." },
  Shammai_HaZaken:   { avatar: "📐", flair: "Av Beis Din", bio: "Shammai the Elder. Keeps a builder's cubit handy. Strict, even about newborns and sukkah." },
  Beis_Shammai:      { avatar: "🏛️", flair: "school of Shammai", bio: "The school of Shammai. Usually outvoted. Stands by every word." },
  Beis_Hillel:       { avatar: "🕊️", flair: "school of Hillel", bio: "The school of Hillel. Usually the halacha. Quotes the other side first." },
  R_Elazar_ben_Azarya: { avatar: "🧑‍🦳", flair: "Tanna", bio: "Made Nasi young. Found the fine print in “before Hashem you shall be purified.”" },
  R_Yitzchak:        { avatar: "📝", flair: "Amora", bio: "Amora. Has a whole page of Rosh Hashana rulings, each one starting “And R' Yitzchak said.”" },
  R_Simlai:          { avatar: "🧵", flair: "Amora", bio: "Amora. Counted the 613 mitzvos. Noticed the Torah starts and ends with chesed." },
  R_Chama_bar_Chanina: { avatar: "🔥", flair: "Amora", bio: "Amora. Explains how to walk after a consuming fire: copy His ways." },
  Queen_Helene:      { avatar: "🏰", flair: "Queen", bio: "Mother of King Munbaz. Gave a gold chandelier for the Heichal entrance. Seven sons, one very tall sukkah." },
  Kimchis:           { avatar: "🧕", flair: "mother of seven Kohanim Gedolim", bio: "All seven sons served as Kohen Gadol. The beams of her house never saw her hair." },
  R_Yishmael_ben_Kimchis: { avatar: "🖐️", flair: "Kohen Gadol (usually)", bio: "Kohen Gadol with enormous hands. Twice got spattered in the market, and twice a brother filled in." },
  Yeshevav_ben_Kimchis: { avatar: "🔁", flair: "Kohen Gadol (fill-in)", bio: "Filled in for his brother once. Their mother was there." },
  Yosef_ben_Kimchis: { avatar: "🔁", flair: "Kohen Gadol (fill-in)", bio: "Filled in for his brother the other time." },
  Yoma_47a:          { avatar: "📄", flair: "Gemara", bio: "The page of Gemara about Kimchis and her seven sons." },
  Yoma_82a:          { avatar: "📄", flair: "Gemara", bio: "The page of Gemara on children and the Yom Kippur fast. Three opinions on the ages." },
  Gemara_Sukkah:     { avatar: "📄", flair: "Gemara", bio: "Masechta Sukkah. Knows the rules on huts, lulavim, and who counts as a kid." },

  // ---- Rishonim & Acharonim ----
  Tur:               { avatar: "🏷️", flair: "Rishon", bio: "R' Yaakov ben Asher. Sorted halacha into four rows. Knows why the sukkah is in Tishrei." },
  Shulchan_Aruch:    { avatar: "🍽️", flair: "Mechaber", bio: "R' Yosef Karo. Set the table. Short answers." },
  Rema:              { avatar: "🧺", flair: "Acharon", bio: "R' Moshe Isserles of Cracow. Adds the tablecloth to the Shulchan Aruch." },
  Rema_fan:          { avatar: "🥯", flair: "Ashkenazi", bio: "Follows the Rema. Will tell you when Sefardim do it differently." },
  Gra_reader:        { avatar: "🕯️", flair: "Vilna", bio: "Reads the Vilna Gaon so you don't have to. (You should, though.)" },
  Tosafos:           { avatar: "➕", flair: "Baalei HaTosafos", bio: "French and German Rishonim. A question on the page, an answer from across Shas." },
  Mishna_Berura:     { avatar: "📓", flair: "Acharon", bio: "R' Yisrael Meir Kagan, the Chafetz Chaim. Explains the Shulchan Aruch line by line." },
  Kitzur_Shulchan_Aruch: { avatar: "📒", flair: "Acharon", bio: "R' Shlomo Ganzfried. The Shulchan Aruch in short, for everyone." },

  // ---- Temple staff & shul regulars ----
  KohenGadol:        { avatar: "💎", flair: "Kohen Gadol", bio: "Once a year I walk into the Holy of Holies. Seven days of prep. Please don't mention Shemaya and Avtalyon." },
  Yerushalmi_gvir:   { avatar: "🏙️", flair: "Jerusalem notable", bio: "One of Jerusalem's important men. Stays up all Yom Kippur night learning, so the city is never quiet enough for the Kohen Gadol to doze." },
  young_kohen_22:    { avatar: "🫰", flair: "kohen · night shift", bio: "Young kohen. Snaps fingers professionally, once a year." },
  Levi_on_the_steps: { avatar: "🪜", flair: "Levi", bio: "Levi. Sings on the fifteen steps. Has seen some things at the Simchas Beis HaSho'eivah." },
  Chazzan_Neilah:    { avatar: "🎼", flair: "shaliach tzibbur", bio: "Leads Kol Nidrei and Neilah. Voice gone by Havdalah." },
  Chazzan_Mincha:    { avatar: "🎵", flair: "reads it every YK", bio: "Reads Yonah at Mincha on Yom Kippur. Every year. Still gets to the last pasuk and pauses." },
  GabbaiOnDuty:      { avatar: "📋", flair: "gabbai", bio: "Gabbai. Hands out aliyos. Hears every mistake in Shemoneh Esrei." },
  gabbai_ST:         { avatar: "🏳️", flair: "gabbai", bio: "Simchas Torah gabbai. Everybody gets an aliyah. Everybody." },
  baal_koreh:        { avatar: "📏", flair: "baal koreh", bio: "Reads from the Torah. Finishes it and rewinds it on the same morning." },
  AYT_regular:       { avatar: "🙂", flair: "shul regular", bio: "Front row for selichos. Knows every addition to the Ten Days' davening." },
  EY_resident:       { avatar: "🌴", flair: "Eretz Yisrael", bio: "Lives in Eretz Yisrael. One day of Yom Tov, and proud of it." },
  Temple_appointee:  { avatar: "📣", flair: "memuneh", bio: "Temple official. Tells whoever pours the water to raise his hand. Every time." },
  tzeduki_kohen:     { avatar: "🦶", flair: "Tzeduki", bio: "Sadducee kohen. Didn't accept the water libation. Poured it on his feet once. Only once." },
  luach_nerd:        { avatar: "📅", flair: "calendar", bio: "Checks the luach before anyone asks. Knows which days Rosh Hashana can't fall on." },

  // ---- everybody else ----
  throwaway_shvigger: { avatar: "😤", bio: "Brother-in-law of someone who apologizes a lot." },
  OPs_wife:          { avatar: "🙄", bio: "Was right." },
  butcher_story:     { avatar: "🥩", bio: "Retells the story of Rav and the butcher. It doesn't end well for the butcher." },
  not_sure_what_i_said: { avatar: "🤔", bio: "Davens fast. Forgets faster." },
  speedrunner_bochur: { avatar: "⏱️", bio: "Yeshiva bochur. Any% Shemoneh Esrei." },
  still_in_bed:      { avatar: "🛌", bio: "Meant to go to selichos. Still meaning to." },
  curious_levi:      { avatar: "🙋", bio: "Levi with questions." },
  nervous_yisrael:   { avatar: "😬", bio: "Yisrael. Worries on everyone's behalf." },
  first_timer:       { avatar: "🆕", bio: "First Yom Kippur in the Azarah." },
  party_planner:     { avatar: "🎉", bio: "Always asks about the after-party." },
  Avtalyon_fan:      { avatar: "🍿", bio: "Fan of Shemaya and Avtalyon. Brings it up every chance he gets." },
  popcorn_levi:      { avatar: "🍿", bio: "Levi. Here for the drama." },
  borrowed_dress:    { avatar: "👗", bio: "Everyone's white dress was borrowed. That was the point." },
  shadchan_2026:     { avatar: "💍", bio: "Shadchan. Has notes on Tu B'Av." },
  chills:            { avatar: "🥶", bio: "Reads Gemara before selichos. Regrets it." },
  soggy_kugel:       { avatar: "🥘", bio: "Was a kugel. Is a soup." },
  Umos_HaOlam:       { avatar: "🌍", bio: "The nations of the world. Has complaints about the sukkah test." },
  roof_neighbor:     { avatar: "🏠", bio: "Shares a roof with a sukkah. Leaves quietly." },
  both_is_good:      { avatar: "🤷", bio: "Why not both." },
  math_kohen:        { avatar: "🧮", bio: "Kohen. Counts the bulls. Counts them again." },
  curious_cheder_kid: { avatar: "🧒", bio: "Cheder kid. Asks why." },
  Aravah:            { avatar: "🍃", flair: "🍃 no taste no smell", bio: "The willow in the bundle. No taste, no smell, gets its own day." },
  Esrog:             { avatar: "🍋", flair: "citron", bio: "The fancy one. Travels in a velvet box." },
  bnei_melachim:     { avatar: "👑", bio: "Children of the King. Invited to stay one more day." },
  the_one_bull:      { avatar: "🐂", bio: "The single bull of Shemini Atzeres." },
  eved_neeman:       { avatar: "🫗", bio: "A servant who poured his Master a drink. It came back in his face." },
  Rabbi_Nassan:      { avatar: "🔊", flair: "Tanna", bio: "R' Nassan. Once asked Eliyahu what the Holy One did at that moment." },
  study_hall_wall:   { avatar: "🧱", flair: "load-bearing", bio: "A wall in the beis medrash. Still leaning. Out of respect." },
  the_crowns:        { avatar: "✨", flair: "tagin", bio: "The little crowns on the letters of a sefer Torah." },
  eighth_row_regular: { avatar: "💺", bio: "Eighth row, every shiur. Someone was in his seat." },
  kid_on_shoulders:  { avatar: "🚩", bio: "On a father's shoulders every Simchas Torah. Flag in one hand, candy in the other." },
  beinoni_4life:     { avatar: "🟰", bio: "Exactly half merits, half sins. Refreshes the status page daily." },
  shortcut_guy:      { avatar: "🥪", bio: "Eats lunch in the shade of whatever is leaning." },
  ima_of_five:       { avatar: "🍼", flair: "Ima", bio: "Five kids, one sukkah, zero quiet." },
  tired_abba:        { avatar: "😴", flair: "Abba", bio: "Hears “Ima, Ima” at night and pretends he doesn't." },
  shammais_daughter_in_law: { avatar: "👶", flair: "new mom", bio: "Just had a baby. Her father-in-law is Shammai. Part of the ceiling is now schach." },
  beis_peor_garrison: { avatar: "🗺️", flair: "Roman garrison", bio: "Sent to find a grave. It kept being somewhere else." },
});
